# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-08 16:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0002_player_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='image',
            field=models.CharField(default=datetime.datetime(2018, 2, 8, 16, 46, 38, 726000, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='reference_id',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('reference_id', 'league')]),
        ),
    ]
