# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-08 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0003_auto_20180208_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo',
            field=models.CharField(default='l', max_length=200),
            preserve_default=False,
        ),
    ]
