# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2018-02-08 17:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fantasy', '0004_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='reference_id',
            field=models.CharField(max_length=20),
        ),
    ]
